import { Plus, Trash } from "@phosphor-icons/react";
import { useRef } from "react";
import type { ActionColor, ActionDefinition } from "../../types.ts";

type ActionListEditorProps = {
  actions: ActionDefinition[];
  onChange: (actions: ActionDefinition[]) => void;
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

const COLORS: { value: ActionColor | ""; label: string }[] = [
  { value: "", label: "Default (green)" },
  { value: "red", label: "Red" },
  { value: "orange", label: "Orange" },
  { value: "yellow", label: "Yellow" },
  { value: "green", label: "Green" },
  { value: "blue", label: "Blue" },
  { value: "purple", label: "Purple" },
];

function emptyAction(): ActionDefinition {
  return { name: "", label: "", prompt: "" };
}

let nextKeyId = 0;

export function ActionListEditor({ actions, onChange }: ActionListEditorProps) {
  const keysRef = useRef<number[]>(actions.map(() => nextKeyId++));

  // Keep keys in sync with actions length
  while (keysRef.current.length < actions.length) {
    keysRef.current.push(nextKeyId++);
  }

  function updateAction(index: number, partial: Partial<ActionDefinition>) {
    const updated = actions.map((a, i) =>
      i === index ? { ...a, ...partial } : a,
    );
    onChange(updated);
  }

  function handleLabelChange(index: number, label: string) {
    const action = actions[index];
    if (!action) return;
    // Auto-generate name from label unless user has manually edited name
    const wasAutoGenerated =
      action.name === "" || action.name === slugify(action.label);
    const updates: Partial<ActionDefinition> = { label };
    if (wasAutoGenerated) {
      updates.name = slugify(label);
    }
    updateAction(index, updates);
  }

  function addAction() {
    keysRef.current.push(nextKeyId++);
    onChange([...actions, emptyAction()]);
  }

  function removeAction(index: number) {
    if (actions.length <= 1) return;
    keysRef.current.splice(index, 1);
    onChange(actions.filter((_, i) => i !== index));
  }

  return (
    <div className="space-y-4">
      {actions.map((action, index) => (
        <div
          key={keysRef.current[index]}
          className="rounded-lg border border-zinc-200 bg-zinc-50/50 p-3 space-y-2"
        >
          <div className="flex items-start justify-between gap-2">
            <div className="flex-1 grid grid-cols-2 gap-2">
              <label className="block">
                <span className="mb-1 block text-xs font-medium text-zinc-500">
                  Label
                </span>
                <input
                  type="text"
                  value={action.label}
                  onChange={(e) => handleLabelChange(index, e.target.value)}
                  placeholder="Deploy to Prod"
                  className="w-full rounded border border-zinc-200 bg-white px-2 py-1.5 text-sm placeholder:text-zinc-300 focus:border-zinc-400 focus:outline-none"
                />
              </label>
              <label className="block">
                <span className="mb-1 block text-xs font-medium text-zinc-500">
                  Name (URL slug)
                </span>
                <input
                  type="text"
                  value={action.name}
                  onChange={(e) =>
                    updateAction(index, { name: e.target.value })
                  }
                  placeholder="deploy-prod"
                  className="w-full rounded border border-zinc-200 bg-white px-2 py-1.5 text-sm font-mono placeholder:text-zinc-300 focus:border-zinc-400 focus:outline-none"
                />
              </label>
            </div>
            {actions.length > 1 && (
              <button
                type="button"
                onClick={() => removeAction(index)}
                className="mt-5 flex h-7 w-7 items-center justify-center rounded text-zinc-400 hover:bg-red-50 hover:text-red-500"
                title="Remove action"
              >
                <Trash size={14} weight="bold" />
              </button>
            )}
          </div>
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-zinc-500">
              Color
            </span>
            <select
              value={action.color ?? ""}
              onChange={(e) =>
                updateAction(index, {
                  color: (e.target.value || undefined) as
                    | ActionColor
                    | undefined,
                })
              }
              className="h-8 rounded border border-zinc-200 bg-white px-2 py-1 text-sm focus:border-zinc-400 focus:outline-none"
            >
              {COLORS.map((c) => (
                <option key={c.value} value={c.value}>
                  {c.label}
                </option>
              ))}
            </select>
          </label>
          <label className="block">
            <span className="mb-1 block text-xs font-medium text-zinc-500">
              Prompt template
            </span>
            <textarea
              value={action.prompt}
              onChange={(e) => updateAction(index, { prompt: e.target.value })}
              placeholder="Use {{input}} as placeholder for user input"
              rows={3}
              className="w-full rounded border border-zinc-200 bg-white px-2 py-1.5 text-sm placeholder:text-zinc-300 focus:border-zinc-400 focus:outline-none"
            />
          </label>
        </div>
      ))}
      <button
        type="button"
        onClick={addAction}
        className="inline-flex items-center gap-1 text-xs text-zinc-500 hover:text-zinc-700"
      >
        <Plus size={12} weight="bold" />
        Add action
      </button>
    </div>
  );
}
